version: '3.8'

services:
  weibobot:
    build: .
    container_name: weibobot
    restart: always
    volumes:
      - ./history.json:/app/history.json
      - ./stats.json:/app/stats.json
      - ./targets.json:/app/targets.json  
      - /var/run/docker.sock:/var/run/docker.sock  # 允许机器人控制宿主机 Docker
      - ./rsshub.env:/app/rsshub.env
    env_file:
      - .env